# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tsirisha/Projects/JHU_Project/Tools/RIMA/miniconda3/bin/cmake

# The command to remove a file.
RM = /home/tsirisha/Projects/JHU_Project/Tools/RIMA/miniconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tsirisha/Projects/Project2/MetaAssembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tsirisha/Projects/Project2/MetaAssembler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/tsirisha/Projects/JHU_Project/Tools/RIMA/miniconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tsirisha/Projects/JHU_Project/Tools/RIMA/miniconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tsirisha/Projects/Project2/MetaAssembler/CMakeFiles /home/tsirisha/Projects/Project2/MetaAssembler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tsirisha/Projects/Project2/MetaAssembler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mm_index

# Build rule for target.
mm_index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mm_index
.PHONY : mm_index

# fast build rule for target.
mm_index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/build
.PHONY : mm_index/fast

src/bio_alphabet.o: src/bio_alphabet.cpp.o
.PHONY : src/bio_alphabet.o

# target to build an object file
src/bio_alphabet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/bio_alphabet.cpp.o
.PHONY : src/bio_alphabet.cpp.o

src/bio_alphabet.i: src/bio_alphabet.cpp.i
.PHONY : src/bio_alphabet.i

# target to preprocess a source file
src/bio_alphabet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/bio_alphabet.cpp.i
.PHONY : src/bio_alphabet.cpp.i

src/bio_alphabet.s: src/bio_alphabet.cpp.s
.PHONY : src/bio_alphabet.s

# target to generate assembly for a file
src/bio_alphabet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/bio_alphabet.cpp.s
.PHONY : src/bio_alphabet.cpp.s

src/loader.o: src/loader.cpp.o
.PHONY : src/loader.o

# target to build an object file
src/loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/loader.cpp.o
.PHONY : src/loader.cpp.o

src/loader.i: src/loader.cpp.i
.PHONY : src/loader.i

# target to preprocess a source file
src/loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/loader.cpp.i
.PHONY : src/loader.cpp.i

src/loader.s: src/loader.cpp.s
.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/loader.cpp.s
.PHONY : src/loader.cpp.s

src/main_index.o: src/main_index.cpp.o
.PHONY : src/main_index.o

# target to build an object file
src/main_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/main_index.cpp.o
.PHONY : src/main_index.cpp.o

src/main_index.i: src/main_index.cpp.i
.PHONY : src/main_index.i

# target to preprocess a source file
src/main_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/main_index.cpp.i
.PHONY : src/main_index.cpp.i

src/main_index.s: src/main_index.cpp.s
.PHONY : src/main_index.s

# target to generate assembly for a file
src/main_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/main_index.cpp.s
.PHONY : src/main_index.cpp.s

src/minimizer.o: src/minimizer.cpp.o
.PHONY : src/minimizer.o

# target to build an object file
src/minimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/minimizer.cpp.o
.PHONY : src/minimizer.cpp.o

src/minimizer.i: src/minimizer.cpp.i
.PHONY : src/minimizer.i

# target to preprocess a source file
src/minimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/minimizer.cpp.i
.PHONY : src/minimizer.cpp.i

src/minimizer.s: src/minimizer.cpp.s
.PHONY : src/minimizer.s

# target to generate assembly for a file
src/minimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/minimizer.cpp.s
.PHONY : src/minimizer.cpp.s

src/murmur3.o: src/murmur3.cpp.o
.PHONY : src/murmur3.o

# target to build an object file
src/murmur3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/murmur3.cpp.o
.PHONY : src/murmur3.cpp.o

src/murmur3.i: src/murmur3.cpp.i
.PHONY : src/murmur3.i

# target to preprocess a source file
src/murmur3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/murmur3.cpp.i
.PHONY : src/murmur3.cpp.i

src/murmur3.s: src/murmur3.cpp.s
.PHONY : src/murmur3.s

# target to generate assembly for a file
src/murmur3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/murmur3.cpp.s
.PHONY : src/murmur3.cpp.s

src/seq_index.o: src/seq_index.cpp.o
.PHONY : src/seq_index.o

# target to build an object file
src/seq_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/seq_index.cpp.o
.PHONY : src/seq_index.cpp.o

src/seq_index.i: src/seq_index.cpp.i
.PHONY : src/seq_index.i

# target to preprocess a source file
src/seq_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/seq_index.cpp.i
.PHONY : src/seq_index.cpp.i

src/seq_index.s: src/seq_index.cpp.s
.PHONY : src/seq_index.s

# target to generate assembly for a file
src/seq_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mm_index.dir/build.make CMakeFiles/mm_index.dir/src/seq_index.cpp.s
.PHONY : src/seq_index.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mm_index"
	@echo "... src/bio_alphabet.o"
	@echo "... src/bio_alphabet.i"
	@echo "... src/bio_alphabet.s"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/main_index.o"
	@echo "... src/main_index.i"
	@echo "... src/main_index.s"
	@echo "... src/minimizer.o"
	@echo "... src/minimizer.i"
	@echo "... src/minimizer.s"
	@echo "... src/murmur3.o"
	@echo "... src/murmur3.i"
	@echo "... src/murmur3.s"
	@echo "... src/seq_index.o"
	@echo "... src/seq_index.i"
	@echo "... src/seq_index.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

